config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    resources :items, only: [:show, :index, :edit, :new, :create, :update]

    resources :orders, only: [:index, :show, :update]
    patch '/orders/:order_id/order_details/:id' => 'orders#order_detail_update',as: 'order_detail_update'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    get '/admins/homes/top' => "homes#top", as: 'top'
  end



  namespace :customers do
    get '/homes/about' => 'homes#about'
    get '/orders/finish' => 'orders#finish'
    post '/orders/check' => 'orders#check'
    get '/customers/:id/exit' => 'customers#exit'
    delete '/customers/customer_id/cart_items' => 'cart_items#destroy_all'
    resources :orders, only: [:index, :show, :new, :create]
    resources :customers, only: [:show, :edit, :update, :destroy]
    resources :shipping_addresses, only: [:edit, :create, :update, :destroy]
    get '/customers/customers_id/shipping_addresses' => 'shipping_addresses#index'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    # get '/customers/customer_id/cart_items' => "cart_items#index"
    resources :items, only: [:index, :show]
  end


  root "customers/homes#top"


  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer
	belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  acts_as_paranoid

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
 class Item < ApplicationRecord
	attachment :image
	has_many :order_details, dependent: :destroy
	has_many :cart_items, dependent: :destroy
	belongs_to :genre
    enum sales_status: {
   	"販売中": true, "売切れ": false
    }
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	has_many :order_details, dependent: :destroy	
	enum payment_method:{
		"クレジットカード": 1, "銀行振込": 2
	}
	enum order_status:{
		"入金待ち": 1, "入金確認": 2, "製作中": 3, "発送準備中": 4, "発送済み": 5
	}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :item


	enum production_status:{
		"着手不可": 1, "制作待ち": 2, "製作中": 3, "製作完了": 4,
	   }

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
	belongs_to :customer

	def view_post_code_and_address_and_name
		self.post_code + self.address +  self.name
	end

	validates :name, presence: true
	validates :post_code, presence: true
	validates :address, presence: true
end
 

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
  	@genre = Genre.new
  	@genres = Genre.all
  end

  def create
  	genre = Genre.new(genre_params)
  	genre.save
  	redirect_to admins_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admins_genres_path
  end

  private
  def genre_params
  	params.require(:genre).permit(:genre_name, :display_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		root_path
	end

    def after_sign_out_path_for(resource)
       admin_session_path
    end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit :sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :email]
      devise_parameter_sanitizer.permit :sign_in, keys: [:email, :password]
    end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/admins/genres/edit.html.erb
<h2>ジャンル編集</h2>
 <%= form_with(model:@genre, url:admins_genre_path(@genre.id), local: true) do |f| %>
      <div class="col-xs-8">
      <strong>ジャンル</strong>
      
        <%= f.text_field :genre_name %>
        <%= f.radio_button :display_status, :true %>
        <%= f.label :display_status, "有効", {value: :true} %>
        <%= f.radio_button :display_status, :false %>
        <%= f.label :display_status, "無効", {value: :false} %>
      </div>
        <div class="col-xs-2">
        <%= f.submit "変更を保存する", class:"btn btn-info" %>
      </div>
      <% end %><br>

app/views/admins/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10">
      <h2>ジャンル追加・一覧</h2>

      <%= form_with(model:@genre, url:admins_genres_path, local: true) do |f| %>
      <div class="col-xs-8">
      <strong>ジャンル</strong>
      
        <%= f.text_field :genre_name %>
        <%= f.radio_button :display_status, :true %>
        <%= f.label :display_status, "有効", {value: :true} %>
        <%= f.radio_button :display_status, :false %>
        <%= f.label :display_status, "無効", {value: :false} %>
      </div>
        <div class="col-xs-2">
        <%= f.submit "追加", class:"btn btn-info" %>
      </div>
      <% end %><br>

        <table class="table">
          <thead>
            <tr>
              <th>ジャンル</th>
              <th>状態</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          <% if @genres.present? %>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.genre_name %></td>
              <% if genre.display_status %>
                <td>有効</td>
              <% else %>
                <td>無効</td>
              <% end %>
              <td><%= link_to "編集する", edit_admins_genre_path(genre), class:"btn btn-info" %></td>
            </tr>
           <% end %>
           <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>