config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    resources :items, only: [:show, :index, :edit, :new, :create, :update]

    resources :orders, only: [:index, :show, :update]
    patch '/orders/:order_id/order_details/:id' => 'orders#order_detail_update',as: 'order_detail_update'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    get '/admins/homes/top' => "homes#top", as: 'top'
  end



  namespace :customers do
    get '/homes/about' => 'homes#about'
    get '/orders/finish' => 'orders#finish'
    post '/orders/check' => 'orders#check'
    get '/customers/:id/exit' => 'customers#exit'
    delete '/customers/customer_id/cart_items' => 'cart_items#destroy_all'
    resources :orders, only: [:index, :show, :new, :create]
    resources :customers, only: [:show, :edit, :update, :destroy]
    resources :shipping_addresses, only: [:edit, :create, :update, :destroy]
    get '/customers/customers_id/shipping_addresses' => 'shipping_addresses#index'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    # get '/customers/customer_id/cart_items' => "cart_items#index"
    resources :items, only: [:index, :show]
  end


  root "customers/homes#top"


  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer
	belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  acts_as_paranoid

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
 class Item < ApplicationRecord
	attachment :image
	has_many :order_details, dependent: :destroy
	has_many :cart_items, dependent: :destroy
	belongs_to :genre
    enum sales_status: {
   	"販売中": true, "売切れ": false
    }
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	has_many :order_details, dependent: :destroy	
	enum payment_method:{
		"クレジットカード": 1, "銀行振込": 2
	}
	enum order_status:{
		"入金待ち": 1, "入金確認": 2, "製作中": 3, "発送準備中": 4, "発送済み": 5
	}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :item


	enum production_status:{
		"着手不可": 1, "制作待ち": 2, "製作中": 3, "製作完了": 4,
	   }

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
	belongs_to :customer

	def view_post_code_and_address_and_name
		self.post_code + self.address +  self.name
	end

	validates :name, presence: true
	validates :post_code, presence: true
	validates :address, presence: true
end
 

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
  	@items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
  	@item = Item.new
    @genre = Genre.where(display_status: true)
  end

  def create
  	@item = Item.new(item_params)
    @item.save
    redirect_to admins_items_path
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.where(display_status: true)
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    # binding.pry
    redirect_to admins_item_path(@item.id)
  end

  private
  def item_params
  	params.require(:item).permit(:name, :price, :description, :genre_id, :image, :sales_atatus)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		root_path
	end

    def after_sign_out_path_for(resource)
       admin_session_path
    end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit :sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :email]
      devise_parameter_sanitizer.permit :sign_in, keys: [:email, :password]
    end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  # def index
  # 	@genres = Genre.where(display_status: true)
  # 	if params[:genre].blank?
  # 	 	@items = Item.where(sales_atatus: true)
  #     @text = "商品"
  # 	else
  # 		@items = Item.where(genre_id: params[:genre]).where(sales_atatus: true)
  #     @text = Genre.find(params[:genre]).genre_name
  # 	end
  # end

  def index
    @genres = Genre.where(display_status: true)
    if params[:genre].blank?
      @items_all = Item.where(sales_status: true)
      @text = "商品"
      @items = []
      @items_all.each do |item|
        if item.genre.display_status == true
          @items << item
        end
      end
    else
      @items_all = Item.where(genre_id: params[:genre]).where(sales_status: true)
      @text = Genre.find(params[:genre]).genre_name
      @items = []
      @items_all.each do |item|
        if item.genre.display_status == true
          @items << item
        end
      end
    end
    
  end


  def show
  	 @item = Item.find(params[:id])
  	 @genres = Genre.all
  	 @cart_item = CartItem.new
  end

end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/admins/items/edit.html.erb
<div class="container">
  <div class="row">
  	<%= form_for(@item, url: admins_item_path(@item.id)) do |f| %>
	<div class="col-xs-4">
	  <h1>商品編集</h1>	  
	  <%= attachment_image_tag @item, :image, :fill, 200,200, format: "jpg" %>
	  <%= f.attachment_field :image %>
	</div>
	<div class="col-xs-8">
		<tbody>
		  <th>
			<tr>
			  <td>
			  <h4>商品名</h4>
			  <%= f.text_field :name, size: "30x10" %>
			  </td>
			  <td>
			  <h4>商品説明</h4>
			  <%= f.text_area :description, size: "32x6" %>
			  </td>
			  <td>
			  <h4>ジャンル</h4>
			  <%= f.collection_select :genre_id, @genre, :id ,:genre_name, :prompt => "--選択してください--" %>
			  </td>
			  <td>
			  <h4>税抜価格</h4>
			  <%= f.text_field :price, size: "30x10" %>
			  </td>
			  <td>
			  <h4>販売ステータス</h4>
			  <%= f.select :sales_status, [["販売中","販売中"], ["売切れ", "売切れ"]], :include_blank =>"--選択してください--" %>
			  </td><br>
			  <%= f.submit "登録", class:"touroku-action btn btn-info" %>
			</tr>
		  </th>
		</tbody>
    </div>
    <% end %>
  </div>
</div>

app/views/admins/items/index.html.erb
<div class="container">
 <div class="row">
  <h1>商品一覧</h1>
  <div class="col-xs-offset-11">
  <%= link_to "商品追加+", new_admins_item_path, class: "btn btn-info" %> 
</div>
  <table class="table">
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税込価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
    <% if @items.present? %>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admins_item_path(item.id) %></td>
        <td><%= item.price %></td>
        <td><%= item.genre.genre_name %></td>
        <td><%= item.sales_status %></td>
      </tr>
    <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admins/items/new.html.erb
<div class="container">
  <div class="row">
  	<h1>商品　新規登録</h1>
	<div class="col-xs-8 col-xs-offset-4">
	<%= form_for(@item, url:admins_items_path) do |f| %>
		<tbody>
			<tr>
			  <td>
			  	<%= attachment_image_tag @item, :image, :fill, 200,200, format: "jpg" %>
                <%= f.attachment_field :image %>
			  </td>

			  <td>
			  　　<h4>商品名</h4>
			  　　<%= f.text_field :name, size: "30x10" %>
			  </td>
			  <td>
			  　　<h4>商品説明</h4>
			  　　<%= f.text_area :description, size: "32x6" %>
			  </td>
			  <td>
			  　　<h4>ジャンル</h4>
			  　　<%= f.collection_select :genre_id, @genre, :id ,:genre_name, :prompt => "--選択してください--" %>
			  </td>
			  <td>
			  <h4>税抜価格</h4>
			  <%= f.text_field :price, size: "30x10" %>
			  </td>
			  <td>
			  <h4>販売ステータス</h4>
        <%= f.select :sales_status, [["販売中","販売中"], ["売切れ", "売切れ"]], :include_blank =>"--選択してください--" %>
			  </td><br>
			  <%= f.submit "登録", class:"touroku-action btn btn-info" %>
			</tr>
		</tbody>
	<% end %>
    </div>
  </div>
</div>

app/views/admins/items/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-4">
		<h2>商品詳細</h2>
			<%= attachment_image_tag @item, :image, :fill, 200,200, format: "jpeg" %>
		</div>
		<div class="col-xs-8">
			<div class="row">
			  <div class="col-xs-3">
			    <h4>商品名</h4>
			  </div>
			    <div class="col-xs-5">
			      <span><h4><%= @item.name %></h4></span>
			    </div>
		    </div>
		    <div class="row">
			  <div class="col-xs-3">
			    <h4>商品説明</h4>
			  </div>
			  <div class="col-xs-7">
			    <span><h4><%= @item.description %></h4></span>
			  </div>
			</div>
			<div class="row">
			  <div class="col-xs-3">
		        <h4>ジャンル</h4>
		      </div>
		      <div class="col-xs-5">
			    <span><h4><%= @item.genre.genre_name %></h4></span>
			  </div>
			</div>
			<div class="row">
		      <div class="col-xs-3">
				<h4>税込価格</h4>
			  </div>
			  <div class="col-xs-5">
			    <span><h4><%= @item.price %>円</h4></span>
			  </div>
		    </div>
		    <div class="row">
		      <div class="col-xs-3">
			    <h4>販売ステータス</h4>
			  </div>
			  <div class="col-xs-5">
			    <span><h4><%= @item.sales_status %></h4></span>
              </div>
              <div class="col-xs-3">
			    <%= link_to "編集する", edit_admins_item_path(@item.id), class:"btn btn-info" %>
			  </div>
		    </div>
		</div>