config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    resources :items, only: [:show, :index, :edit, :new, :create, :update]

    resources :orders, only: [:index, :show, :update]
    patch '/orders/:order_id/order_details/:id' => 'orders#order_detail_update',as: 'order_detail_update'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    get '/admins/homes/top' => "homes#top", as: 'top'
  end



  namespace :customers do
    get '/homes/about' => 'homes#about'
    get '/orders/finish' => 'orders#finish'
    post '/orders/check' => 'orders#check'
    get '/customers/:id/exit' => 'customers#exit'
    delete '/customers/customer_id/cart_items' => 'cart_items#destroy_all'
    resources :orders, only: [:index, :show, :new, :create]
    resources :customers, only: [:show, :edit, :update, :destroy]
    resources :shipping_addresses, only: [:edit, :create, :update, :destroy]
    get '/customers/customers_id/shipping_addresses' => 'shipping_addresses#index'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    # get '/customers/customer_id/cart_items' => "cart_items#index"
    resources :items, only: [:index, :show]
  end


  root "customers/homes#top"


  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer
	belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  acts_as_paranoid

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
 class Item < ApplicationRecord
	attachment :image
	has_many :order_details, dependent: :destroy
	has_many :cart_items, dependent: :destroy
	belongs_to :genre
    enum sales_status: {
   	"販売中": true, "売切れ": false
    }
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	has_many :order_details, dependent: :destroy	
	enum payment_method:{
		"クレジットカード": 1, "銀行振込": 2
	}
	enum order_status:{
		"入金待ち": 1, "入金確認": 2, "製作中": 3, "発送準備中": 4, "発送済み": 5
	}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :item


	enum production_status:{
		"着手不可": 1, "制作待ち": 2, "製作中": 3, "製作完了": 4,
	   }

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
	belongs_to :customer

	def view_post_code_and_address_and_name
		self.post_code + self.address +  self.name
	end

	validates :name, presence: true
	validates :post_code, presence: true
	validates :address, presence: true
end
 

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  #before_action :authenticate_admin!
  
  def index
    @orders= Order.all
  end

  def show
    @order= Order.find(params[:id])
    @order_detail = @order.order_details
  end

  def update
      order= Order.find(params[:id])
      order.update(order_params)
      redirect_to admins_order_path(order.id)
      
  end

  def order_detail_update
      order_detail= OrderDetail.find(params[:id])
      order_detail.update(order_detail_params)
      redirect_to admins_order_path(order.id) 
  end

  private

 def order_params
   params.require(:order).permit(:order_status)
 end

 def order_detail_params
  params.require(:order_detail).permit(:production_status)
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		root_path
	end

    def after_sign_out_path_for(resource)
       admin_session_path
    end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit :sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :email]
      devise_parameter_sanitizer.permit :sign_in, keys: [:email, :password]
    end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  before_action :authenticate_customer!
  def new
    @order = Order.new
    @shipping_address = ShippingAddress.where(customer_id: current_customer.id)
    @customer = current_customer
    end

  def index
    @orders = Order.where(customer_id: current_customer.id)
  end


  def show
    @order = Order.find(params[:id])
    @order_detail = @order.order_details
    if current_customer.id != @order.customer.id
      redirect_to customers_customer_path(current_customer.id)
      end
  end

  def finish
  end

  def check
    # if params[:address] == "3"
       # params[:new_post_code][:new_address][:new_name].blank?
       # redirect_to new_customers_order_path
    # end
    
     @order = Order.new
     @total_price = params[:order][:total_price]
     @cart_items = current_customer.cart_items
     @payment_method = params[:order][:payment_method]
    if params[:order][:address] == "1"
      @name = current_customer.last_name + " " + current_customer.first_name
      @post_code = current_customer.post_code
      @address = current_customer.address
    elsif params[:order][:address] == "2"
      shipping_address = ShippingAddress.find(params[:order][:address_id].to_i)
      @post_code = shipping_address.post_code
      @address = shipping_address.address
      @name = shipping_address.name
    else
      @address = params[:order][:new_address]
      @post_code = params[:order][:new_post_code]
      @name = params[:order][:new_name]
      # binding.pry
    end
    # redirect_to customers_orders_check_path
  end

  def create
    cart_items = current_customer.cart_items
    order = Order.new(order_params)
    order.customer_id = current_customer.id
    order.save
    cart_items.each do |cart_item|
    order_detail= OrderDetail.new
    order_detail.item_id = cart_item.item_id
    order_detail.quantity = cart_item.quantity
    order_detail.price = cart_item.item.price
    order_detail.order_id = order.id
    order_detail.save
    end
    cart_items.destroy_all
    redirect_to customers_orders_finish_path
  end


  private
  def order_params
    params.require(:order).permit(:payment_method, :address, :post_code,:name, :total_price)
  end
end
 

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/admins/orders/index.html.erb
<div class="contianer">
    <div class="row">
    　　<div class="col-md-7 col-md-offset-1">
       　　 <h2>注文履歴一覧画面</h2>
        　　<table class="table table-hover table-inverse">
        　<thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <% @orders.each do |order| %>
        <tbody>
          <tr>
          
          <th><%= link_to order.created_at.to_s(:datetime_jp), admins_order_path(order.id) %></th>
          <th><%= order.customer.last_name %> <%= order.customer.first_name %></th>
          
            <th>
              <%= order.order_details.sum(:quantity) %>
              </th>
          <th><%= order.order_status %></th>
          </tr>
        </tbody>
      <% end %>
     </table>
     </div>
  </div>
</div>

app/views/admins/orders/show.html.erb
<div class="contianer">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-2">
    <h2>注文詳細画面</h2>
    <table>
    <tbody>
    <th>
      <tr>
     　　<td>
        <h4>購入者</h4>
        </td>
        <td>
        　<%= link_to admins_customer_path(@order.customer.id) do %>
          <%= @order.customer.last_name %>
          <%= @order.customer.first_name %>
          <% end %>
        </td>
      </tr>
      </tr>
      <tr>
        <td>
        <h4>配送先</h4>
        </td>
        <td>
        <%= @order.post_code %>
        <%= @order.address %>
        <%= @order.name %>
        </td>
      </tr>
      <tr>
        <td>
        <h4>支払い方法</h4>
        </td>
        <td><%= @order.payment_method %></td>
      </tr>
      <tr>
      
        <td>
        <h4>注文ステータス</h4>
        </td><br>
        <%= form_for(@order, url: admins_order_path(@order.id)) do |f| %>
        <td>
          <%= f.select :order_status, Order.order_statuses.keys.to_a %>
          <%= f.submit "更新", class: "btn btn-info" %>
        </td>
        <% end %>
        </tr>
    </th>
  </tbody>
 </table>
    </div>
  </div>
<div class="row">
  <div class="col-xs-6 col-xs-offset-2">
    <table class="table table-inverse">
      <thead>
        <tr>
        　　<th>商品名</th>
        　　<th>単価(税込)</th>
            <th>数量</th>
        　　<th>小計</th>
        　　<th>製作ステータス</th>
        </tr>
      </thead>
      <tbody>
      <tr>
      <% @order_detail.each do |order| %>
          <td><%= order.item.name %></td>
          <td><span>¥</span><%= order.price %></td>
          <td><%= order.quantity %></td>
          <td><%= order.quantity * order.price %></td>
          <%= form_for order, url:  admins_order_detail_update_path(@order, order) do |f| %>
            <td><%= f.select :production_status, OrderDetail.production_statuses.keys.to_a %>
            <%= f.submit "更新", class: "btn btn-info" %>
            </td>
            <% end %>
       
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-xs-4">
  <table>
  <tbody>
  <th>
    <tr>
     
      <td><h4>商品合計</h4></td>
      <td><h4> <%= @order.total_price %>円</h4></td>
    </tr>  	       
     <td><h4>配送料</td>
     <td><h4><%= @order.postage %>円</h4></td>
  </tr>
  <tr>
    <td><h4>ご請求額</td>
    <td><h4> <%= @order.total_price + @order.postage %>円</h4></td>
  </tr>
  </th>
  </tbody>
  </table>
</div>
</div>